import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import { montseratt, openSans } from "./config/fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={clsx(
        "min-h-screen bg-background antialiased dark",
        openSans.variable,
        montseratt.variable
      )}
    >
      <body
        className={`antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
